server:
  port: 9088
eureka:
  instance:
    hostname: spring1
  server:
    # see discussion about enable-self-preservation:
    # https://github.com/jhipster/generator-jhipster/issues/3654
    enable-self-preservation: false
    registry-sync-retry-wait-ms: 500
    a-sgcache-expiry-timeout-ms: 60000
    eviction-interval-timer-in-ms: 30000
    peer-eureka-nodes-update-interval-ms: 30000
    renewal-threshold-update-interval-ms: 15000
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8088/eureka/