version: '2'
services:
    mutidatasources-app:
        image: mutidatasources
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mutidatasources-mysql:3306/mutidatasources?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mutidatasources-mysql:
        extends:
            file: mysql.yml
            service: mutidatasources-mysql
